apiVersion: v1
entries:
  bagofwords:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2025-05-04T06:34:29.835376+03:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.3.2
    description: Bag of words - a new ai data tool
    digest: 896cbb7500f7fc22babbc599e113abca3aa55200971b83163ff6bf03aeb22f9c
    name: bagofwords
    type: application
    urls:
    - https://bagofwords.com/helm/bagofwords-1.0.1.tgz
    version: 1.0.1
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r34
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.16.0-debian-12-r2
        - name: postgresql
          image: docker.io/bitnami/postgresql:17.2.0-debian-12-r3
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 17.2.0
    created: "2025-05-04T06:34:29.838218+03:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 78165a640a64b0b34f8d34a7d4b302f867c87a3c00d692119147e8395f2511c5
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - https://bagofwords.com/helm/charts/postgresql-16.3.2.tgz
    version: 16.3.2
generated: "2025-05-04T06:34:29.831224+03:00"
